#!/bin/bash
~/bin/screen/default.sh
# xset +fp /home/efazati/.fonts
#xset fp rehash
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,ir
#feh --bg-fill ~/Pictures/background/wallpaper-base.jpg
~/bin/background.sh
#setxkbmap -layout us
#wqautocutsel
