#!/bin/bash
#xrandr --output VGA1 --left-of HDMI1
xset +fp /home/efazati/.fonts
xset fp rehash
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,ir
#feh --bg-fill ~/Pictures/background/wallpaper-base.jpg
autocutsel
